name: "Codeowners Approval Workflow"
on:
  pull_request_review:
    types: [submitted]

jobs:
  codeowners-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Codeowners Multi-Approval Check
        uses: noamelf/codeowner-multi-approval-action@v0.1
        with:
          pr-number: ${{ github.event.pull_request.number }}
          repo-name: ${{ github.repository }}
          github-token: ${{ secrets.MULTI_APPROVAL_GH_TOKEN }}
